version: '3'

services:
  blog_application:
    depends_on:
      - blog_postgresql_db
    container_name: blog_application
    stdin_open: true
    tty: true
    restart: always
    build: .
    ports:
      - 9999:9999
    command: >
      sh -c "uvicorn blogs.main:app --host 0.0.0.0 --port 9999 --reload"
    volumes:
      - ./application:/application
    env_file:
      - .env

  blog_postgresql_db:
    container_name: blog_postgresql_db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:
